"""add created_at to comments

Revision ID: c005d23a8085
Revises: bcfb3c3fe95b
Create Date: 2025-08-16 19:47:29.186235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c005d23a8085'
down_revision: Union[str, Sequence[str], None] = 'bcfb3c3fe95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'cover_image',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='博客封面图片URL',
               existing_nullable=True)
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'created_at')
    op.alter_column('blogs', 'cover_image',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='博客封面图片URL',
               existing_nullable=True)
    # ### end Alembic commands ###
